<?php
namespace NpAppTest\Bootstrap;

use NpApp\Bootstrap\Env;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-08 at 10:56:17.
 */
class EnvTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Env
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Env;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Flower\Bootstrap\Env::setEnv
     */
    public function testSetEnv()
    {
        $this->object->setEnv('foo', 'bar');
        $this->assertEquals('bar', $this->object->foo);
    }

    /**
     * @covers Flower\Bootstrap\Env::getEnv
     */
    public function testGetEnv()
    {
        $this->object->setEnv('foo', 'bar');
        $this->assertEquals('bar', $this->getEnv('foo'));
    }

    /**
     * @covers Flower\Bootstrap\Env::setEnvs
     */
    public function testSetEnvs()
    {
        $envs = array(
            'foo' => 'bar',
        );
        $this->object->setEnvs($envs);
        $this->assertEquals('bar', $this->object->foo);
    }
}
