        <div  ng-view  class="view-animate"></div>        
        <div id="c1" data-target="c1">content1<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>.</div>
        <div id="c2" data-target="c2">content2<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>.</div>
        <div id="c3" data-target="c3">content3<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>.</div>
        <div id="c4" data-target="c4">content4<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>.</div>
        <div id="c5" data-target="c5">content5<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>.</div>