<?php
if (!isset($collection)) {
    echo "<!-- collection not found -->\n";
    return;
}

$manager = $this->npPaneManager();
$callback = function ($pane, $params = array()) {
    $pane->href = sprintf($pane->href, $params['href']);
    $pane->attributes['gumby-goto'] = sprintf($pane->attributes['gumby-goto'], $params['target']);
    $pane->label = sprintf($pane->label, $params['label']);
    Flower\View\Pane\Factory\AnchorPaneFactory::parseBeginEnd($pane, $params);
};
$pane = $manager->get('gumby/skipLink');
$collection = new Flower\View\Pane\Entity\ApplicatableCallbackCollection($callback, $collection);
$pane->setCollection($collection);
echo '<nav id="sidebar-nav-holder" class="vertical-nav" gumby-pin="[data-target=\'icons\']">' . "\n";
echo $manager->renderPane($pane);
echo '</nav>' . "\n";
?>

<nav class="vertical-nav">
    <ul>
        <li><a href="#/view1">view1</a></li>
        <li><a href="#/view2">view2</a></li>
    </ul>
</nav>