<?php

namespace NpAppTest;

use NpApp\Module;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-29 at 18:15:38.
 */
class ModuleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Module
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Module;
        $this->serviceManager = Bootstrap::getServiceManager();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers NpApp\Module::onBootstrap
     */
    public function testOnBootstrap()
    {

    }

    /**
     * @covers NpApp\Module::getAutoloaderConfig
     */
    public function testGetAutoloaderConfig()
    {

    }

    /**
     * @covers NpApp\Module::getConfig
     * @todo   Implement testGetConfig().
     */
    public function testGetConfig()
    {
        $config = $this->serviceManager->get('Config');
        $this->assertEquals('NpApp\Controller', $config['router']['routes']['home']['options']['defaults']['__NAMESPACE__']);
    }

    /**
     * @covers NpApp\Module::getServiceConfig
     */
    public function testGetServiceConfig()
    {

    }
}
