<div class="pretty navbar fixed" id="nav4">
    <div class="row">
        <a class="toggle" gumby-trigger="#nav4 ul" href="#"><i class="icon-menu"></i></a>
        <h1 class="four columns">
            <a href="#">
                <?php echo nl2br($this->escapeHtml("AngularJS on \nGumbyFramework")); ?>
            </a>
        </h1>
        <?php
        if (!isset($collection)) {
            echo 'collection not found';
        } else {
            $paneManager = $this->npPaneManager();
            $pane = $paneManager->get('navi/naviContainer');
            $collection = new ArrayIterator($collection);
            $pane->setCollection($collection);
            echo $paneManager->renderPane($pane);
        }
        ?>
    </div>
</div>
