<?php
$navId = isset($navId) ? $this->escapeHtmlAttr($navId) : 'nav';
if (!isset($siteData)) {
    $siteData = array();
}
$siteLabel = isset($siteData['site_label']) ? $siteData['site_label'] : 'Demo Site';
?>
<div class="pretty navbar fixed" id="<?php echo $navId?>">
    <div class="row">
        <a class="toggle" gumby-trigger="#<?php echo $navId?> ul" href="#"><i class="icon-menu"></i></a>
        <h1 class="four columns">
            <a href="<?php echo $this->basePath('/')?>">
                <?php
                echo nl2br($this->escapeHtml($siteLabel));
                ?>
            </a>
        </h1>
        <?php
        if (!isset($collection)) {
            echo 'collection not found';
        } else {
            $paneManager = $this->npPaneManager();
            $pane = $paneManager->get('navi/naviContainer');
            $collection = new ArrayIterator($collection);
            $pane->setCollection($collection);
            echo $paneManager->renderPane($pane);
        }
        ?>
    </div>
</div>
